from fastapi.responses import HTMLResponse

def fixture_html(fixed: bool):
    return HTMLResponse('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Acme Admin · ProofPact test target</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f4ef;color:#191c23;font:15px system-ui}main{max-width:900px;padding:32px;margin:auto}h1{letter-spacing:-1px}section{background:white;padding:28px;border:1px solid #ded9cf;border-radius:12px;margin-bottom:20px}label{display:block;margin:16px 0 6px}input{display:block;width:100%;padding:12px;border:1px solid #aaa;border-radius:6px}button{padding:12px 18px;background:#191c23;color:white;border:0;border-radius:6px;margin-top:14px;cursor:pointer}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px 4px;border-bottom:1px solid #eee}.stats{display:flex;gap:24px;flex-wrap:wrap}.stat{flex:1}small{color:#606771}.hint{font-size:12px;color:#606771} [hidden]{display:none!important}</style></head><body><main><small>PROOFPACT / SYNTHETIC TEST TARGET</small><h1>Acme Admin Portal</h1><section id="login"><h2>Welcome back</h2><form id="login-form"><label for="email">Email</label><input id="email" type="email" required><label for="password">Password</label><input id="password" type="password" required><button>Sign in</button><p role="alert" id="error"></p></form><p class="hint">demo@proofpact.local · DemoPass123! · OTP 424242</p></section><section id="otp" hidden><h2>Verify your identity</h2><form id="otp-form"><label for="code">Verification code</label><input id="code" inputmode="numeric" required><button>Verify code</button><p id="otp-error" role="alert"></p></form></section><div id="dashboard" hidden><p data-testid="verified">Identity verified</p><section class="stats"><div class="stat"><small>Total orders</small><h2 data-testid="total-orders">27</h2></div><div class="stat"><small>Total revenue</small><h2 data-testid="revenue">₹54,000</h2></div></section><section><h2>Orders</h2><p>Showing 1–10 of 27 records</p><table><thead><tr><th>Order</th><th>Customer</th><th>Amount</th></tr></thead><tbody id="rows"></tbody></table><button id="export">Export CSV</button><p class="hint">Fixture: VERSION</p></section></div></main><script>
const records=Array.from({length:27},(_,i)=>({id:i+1,customer:'Customer '+(i+1),amount:2000}));
document.querySelector('#login-form').onsubmit=e=>{e.preventDefault();if(document.querySelector('#email').value==='demo@proofpact.local'&&document.querySelector('#password').value==='DemoPass123!'){document.querySelector('#login').hidden=true;document.querySelector('#otp').hidden=false}else document.querySelector('#error').textContent='Invalid credentials'};
document.querySelector('#otp-form').onsubmit=e=>{e.preventDefault();if(document.querySelector('#code').value==='424242'){document.querySelector('#otp').hidden=true;document.querySelector('#dashboard').hidden=false}else document.querySelector('#otp-error').textContent='Invalid code'};
document.querySelector('#rows').innerHTML=records.slice(0,10).map(r=>'<tr><td>#'+r.id+'</td><td>'+r.customer+'</td><td>₹'+r.amount+'</td></tr>').join('');
document.querySelector('#export').onclick=()=>{const csv='id,customer,amount\\n'+records.slice(0,COUNT).map(r=>[r.id,r.customer,r.amount].join(',')).join('\\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='acme-orders.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
</script></body></html>'''.replace('COUNT','27' if fixed else '10').replace('VERSION','fixed · exports all records' if fixed else 'broken · exports current page'))
